import Head from "next/head";
import React, { useState } from "react";
import {
  useAddCategoryMutation,
  useGetCategoriesQuery,
} from "../lib/features/category/categoryApi";

export default function Home() {
  const { data, isError, isLoading, isSuccess } = useGetCategoriesQuery();
  const [addCategory] = useAddCategoryMutation();

  const [name, setName] = useState("");

  if (isLoading) return <div>Loading</div>;
  if (isError) return <div>Error</div>;

  const handleClick = async () => {
    await addCategory({
      name,
    });
  };

  console.log(data?.data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>sdfsdfsdf</p>

      {data?.data?.length > 0 &&
        data?.data?.map((singleData) => (
          <div key={singleData?._id}>{singleData?.name}</div>
        ))}

      <hr />
      <input
        type="text"
        name="name"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <button onClick={handleClick}>Send post req</button>
    </div>
  );
}
